// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgCA9L27Md8gKBcVf9_tkdvDjcN76jorI',
    appId: '1:309502914107:web:d5949b54f5835f17e7361e',
    messagingSenderId: '309502914107',
    projectId: 'ecommerce-app-d91e7',
    authDomain: 'ecommerce-app-d91e7.firebaseapp.com',
    storageBucket: 'ecommerce-app-d91e7.firebasestorage.app',
    measurementId: 'G-6FGHK6WNJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhaS4adOhpilH_37O8qkx3GKaDNiZNuB8',
    appId: '1:309502914107:android:1e0e6e4b7659f2a2e7361e',
    messagingSenderId: '309502914107',
    projectId: 'ecommerce-app-d91e7',
    storageBucket: 'ecommerce-app-d91e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfVJr8nM7QhvhINGIknm0xca4U1baGBvE',
    appId: '1:309502914107:ios:951bf6a0b0362dd4e7361e',
    messagingSenderId: '309502914107',
    projectId: 'ecommerce-app-d91e7',
    storageBucket: 'ecommerce-app-d91e7.firebasestorage.app',
    iosBundleId: 'com.example.ecomerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfVJr8nM7QhvhINGIknm0xca4U1baGBvE',
    appId: '1:309502914107:ios:951bf6a0b0362dd4e7361e',
    messagingSenderId: '309502914107',
    projectId: 'ecommerce-app-d91e7',
    storageBucket: 'ecommerce-app-d91e7.firebasestorage.app',
    iosBundleId: 'com.example.ecomerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgCA9L27Md8gKBcVf9_tkdvDjcN76jorI',
    appId: '1:309502914107:web:e19fdcd356319a4ce7361e',
    messagingSenderId: '309502914107',
    projectId: 'ecommerce-app-d91e7',
    authDomain: 'ecommerce-app-d91e7.firebaseapp.com',
    storageBucket: 'ecommerce-app-d91e7.firebasestorage.app',
    measurementId: 'G-5C53LN9X07',
  );
}
